document.write("</center>");
document.write("<TABLE WIDTH='760' BORDER='0' CELLSPACING='0' CELLPADDING='0' HEIGHT='7' BGCOLOR='#FFFFFF' ALIGN='CENTER'>");
document.write("  <TR> ");
document.write("    <TD WIDTH='8' BGCOLOR='#FFA200' BACKGROUND='http://www.pconline.com.cn/images/new/k_bg_left.gif'><IMG SRC='bottom_l.gif' WIDTH='13' HEIGHT='30'></TD>");
document.write("    <TD WIDTH='744' HEIGHT='20' BACKGROUND='http://www.pconline.com.cn/images/new/bottom_bg.gif'></TD>");
document.write("    <TD WIDTH='8' BGCOLOR='#FFA200' BACKGROUND='http://www.pconline.com.cn/images/new/k_bg_right.gif'><IMG SRC='bottom_r.gif' WIDTH='13' HEIGHT='30'></TD>");
document.write("  </TR>");
document.write("</TABLE>");
document.write("<BR> <TABLE WIDTH='465' BORDER='0' CELLSPACING='0' CELLPADDING='0' CLASS='sfont' ALIGN='center'> ");
document.write("<TR VALIGN='bottom'> ");
document.write("    <TD ALIGN='center' WIDTH='142' HEIGHT='120' VALIGN='TOP'><FONT COLOR='#FFFFFF'><A HREF='http://www.pconline.cn/'><IMG SRC='all_pconline.gif' WIDTH='115' HEIGHT='47' border='0'></a><BR>");
document.write("      </FONT><A");
document.write(" HREF='http://www.gdca.gov.cn/'><FONT COLOR='#FFFFFF'>广东省通信管理局</FONT></A><FONT COLOR='#FFFFFF'> ");
document.write("      <BR>");
document.write("       </FONT><A HREF='http://www.pconline.com.cn/tpy/icp.html' ><FONT COLOR='#FFFFFF'>粤ICP证号:000010</FONT></A> ");
document.write("<FONT COLOR='#FFFFFF'><BR> </FONT></TD>");
document.write("    <TD WIDTH='323' HEIGHT='120' class=sfont><FONT COLOR='#FFFFFF'> 技术支持与报障：support@pconline.com.cn<BR>");
document.write("      　　　　　　　　020-87568837 <BR> ");
document.write("　　　　　　　　</FONT><BR> ");
document.write("<FONT COLOR='#FFFFFF'>对本站有任何建议、意见或投诉，</FONT><A href='http://guide.pconline.com.cn/suggest/post.jsp'><FONT color='#FFFFFF'>请点这里在线提交</FONT></A><FONT COLOR='#FFFFFF'>. ");
document.write("<BR> 本网站简体、繁体两种版本，以简体版为准 <BR> PConline版权所有,未经授权禁止转载、摘编、复制或建立镜像.如有违反,追究法律责任</FONT> ");
document.write("<A href=http://www.pconline.com.cn/"#\" onclick=\"javascript:window.open('http://artc.pconline.com.cn:8001/cms_pconline/article/articleCounterShow.jsp?fromURL=' + window.location +';return false;', '', 'scrollbars=yes,left=100,top=150,width=500,height=350,resizable=yes');\"><Font Color=#303880>__</FONT></A>");
document.write("<BR> </TD></TR> </TABLE>");
