d = new dTree("d");
<!--
d.add("0","-1","Gradle资料","");
d.add("1","0","有了Gradle，还会选Maven吗？","my_data/(WJW)有了Gradle，还会选Maven吗？.html");
d.add("2","0","etcd4j的build.gradle","my_data/etcd4j的build.gradle.html");
d.add("3","0","gradle 3.0 之后新的依赖方式","my_data/gradle_3.0_之后新的依赖方式.htm");
d.add("4","0","gradle中api、implementation和compile的区别","my_data/gradle中api、implementation和compile的区别.htm");
d.add("5","0","一文搞清Gradle依赖","my_data/一文搞清Gradle依赖.htm");
d.add("6","0","Gradle Goodness","");
d.add("7","6","Download Javadoc Files For Dependencies In IDE","my_data/Gradle_Goodness/Download_Javadoc_Files_For_Dependencies_In_IDE.htm");
d.add("8","6","Set Java Compiler Encoding","my_data/Gradle_Goodness/Set_Java_Compiler_Encoding.htm");
d.add("9","6","Use gradlew for Easy Gradle Execution","my_data/Gradle_Goodness/Use_gradlew_for_Easy_Gradle_Execution.htm");
d.add("10","6","Using Gradle for a Mixed Java and Groovy Project","my_data/Gradle_Goodness/Using_Gradle_for_a_Mixed_Java_and_Groovy_Project.htm");
d.add("11","6","Handle Copying Duplicate Files","my_data/Gradle_Goodness/Handle_Copying_Duplicate_Files.htm");
d.add("12","6","Renaming Files while Copying","my_data/Gradle_Goodness/Renaming_Files_while_Copying.htm");
d.add("13","6","Continue Build Even with Failed Tasks","my_data/Gradle_Goodness/Continue_Build_Even_with_Failed_Tasks.htm");
d.add("14","6","Check Task Dependencies With a Dry Run","my_data/Gradle_Goodness/Check_Task_Dependencies_With_a_Dry_Run.htm");
d.add("15","6","Show Standard Out or Error Output from Tests","my_data/Gradle_Goodness/Show_Standard_Out_or_Error_Output_from_Tests.htm");
d.add("16","6","Run Java Application From Build Script","my_data/Gradle_Goodness/Run_Java_Application_From_Build_Script.htm");
d.add("17","6","Running Groovy Scripts as Application","my_data/Gradle_Goodness/Running_Groovy_Scripts_as_Application.htm");
d.add("18","6","Getting More Dependency Insight","my_data/Gradle_Goodness/Getting_More_Dependency_Insight.htm");
d.add("19","6","Unpacking an Archive","my_data/Gradle_Goodness/Unpacking_an_Archive.htm");
d.add("20","6","Get User Input Values From Console","my_data/Gradle_Goodness/Get_User_Input_Values_From_Console.htm");
d.add("21","6","Using Optional Ant Task in Gradle","my_data/Gradle_Goodness/Using_Optional_Ant_Task_in_Gradle.htm");
d.add("22","0","Web","");
d.add("23","22","创建Web应用项目","my_data/web/创建Web应用项目/index.html");
d.add("24","22","使用Gradle构建Java Web应用","my_data/web/(WJW)使用Gradle构建Java Web应用.htm");
d.add("25","22","Eclipse中进行Gradle+Jetty部署的web项目的断点调试","my_data/web/Eclipse中进行Gradle+Jetty部署的web项目的断点调试/index.html");
d.add("26","22","Gradle构建Java Web应用：Servlet依赖与Tomcat插件","my_data/web/Gradle构建Java_Web应用：Servlet依赖与Tomcat插件.htm");
d.add("27","22","Gradle添加tomcat插件","my_data/web/为Gradle添加tomcat插件/index.html");
d.add("28","22","Gradle Tomcat plugin","my_data/web/Gradle_Tomcat_plugin.htm");
d.add("29","0","Gradle用户手册","");
d.add("30","29","1. 简介 - Introduction(已完成)","my_data/Gradle用户手册/1. 简介 - Introduction/1._简介_-_Introduction(已完成).htm");
d.add("31","30","1.1. 关于本手册 - About this user guide","my_data/Gradle用户手册/1. 简介 - Introduction/1._简介_-_Introduction(已完成).htm");
d.add("32","29","2. 概述 - Overview","my_data/Gradle用户手册/2. 概述 - Overview/2._概述_-_Overview.htm");
d.add("33","32","2.1. Features","");
d.add("34","32","2.2. Why Groovy?","");
d.add("35","29","3.教程说明 - Tutorials(已完成)","");
d.add("36","35","3.1. 快速开始 - Getting Started","");
d.add("37","29","4. 安装 - Installing Gradle(已完成)","");
d.add("38","37","4.1. 先决条件 - Prerequisites","");
d.add("39","37","4.2. 下载 - Download","");
d.add("40","37","4.3. 解压 - Unpacking","");
d.add("41","37","4.4. 环境变量配置 - Environment variables","");
d.add("42","37","4.5. 安装测试 - Running and testing your installation","");
d.add("43","37","4.6. JVM参数配置 - JVM options","");
d.add("44","0","Gradle一般使用常见问答","my_data/Gradle一般使用常见问答.htm");
d.add("45","0","Gradle Wrapper 引用本地的发布包","my_data/(WJW)GradleWrapper引用本地的发布包.html");
d.add("46","0","Gradle中的buildScript代码块","my_data/Gradle中的buildScript代码块/index.html");
d.add("47","0","(WJW)Gradle使用maven本地仓库","my_data/(WJW)Gradle使用maven本地仓库.htm");
d.add("48","0","Gradle修改Maven仓库地址","my_data/Gradle修改Maven仓库地址.htm");
d.add("49","0","gradle运行java main","my_data/gradle运行java main.html");
d.add("50","0","Debug Java program by executing “gradle run”","my_data/Debug Java program by executing “gradle run”.html");
d.add("51","0","gradle传递参数给Java项目的main函数","my_data/gradle传递参数给Java项目的main函数.html");
d.add("52","0","Gradle运行单元测试的各种技巧","my_data/Gradle运行单元测试的各种技巧.htm");
d.add("53","0","如何在 Gradle 中运行 Groovy 的 主类以及测试类","my_data/如何在_Gradle_中运行_Groovy_的_主类以及测试类.htm");
d.add("54","0","gradle 发布jar包到nexus","my_data/gradle_发布jar包到nexus.htm");
d.add("55","0","Gradle打包Groovy脚本成 jar与上传到maven repository","my_data/Gradle打包Groovy脚本成_jar与上传到maven_repository.htm");
d.add("56","0","Gradle_脚本中处理Manifest__ClassPath","my_data/Gradle_脚本中处理Manifest__ClassPath.htm");
d.add("57","0","gradle项目中资源文件的相对路径打包处理技巧(如何不将配置文件打包到jar文件内)","my_data/gradle项目中资源文件的相对路径打包处理技巧(如何不将配置文件打包到jar文件内).html");
d.add("58","0","Gradle build without tests","my_data/Gradle build without tests.htm");
d.add("59","0","Gradle File dependencies","my_data/Gradle_File_dependencies.htm");
d.add("60","0","Gradle 构建工具 介绍","my_data/Gradle_构建工具_介绍.htm");
d.add("61","0","在 Eclipse 下利用 gradle 构建系统","my_data/在 Eclipse 下利用 gradle 构建系统.htm");
d.add("62","0","(wjw)Gradle秘籍","my_data/(wjw)Gradle秘籍.html");
d.add("63","0","(wjw)Gradle构建java项目中加入调试信息","my_data/(wjw)Gradle构建java项目中加入调试信息.htm");
d.add("64","0","Gradle&Git与代码规范利器Checkstyle的完美结合","my_data/Gradle&Git与代码规范利器Checkstyle的完美结合/Gradle&Git与代码规范利器Checkstyle的完美结合.htm");
d.add("65","0","解决Gradle编译时出现： 编码GBK的不可映射字符","my_data/解决Gradle编译时出现：_编码GBK的不可映射字符.htm");
d.add("66","0","Gradle的依赖管理(Repository&Dependency )","my_data/Gradle的依赖管理(Repository&Dependency_).htm");
d.add("67","0","Standard project properties","my_data/Standard_project_properties.htm");
d.add("68","0","使用Gradle 插件进行代码分析","my_data/使用Gradle插件进行代码分析/index.html");
d.add("69","0","Netflix开源的Gradle插件集合","my_data/Netflix开源的Gradle插件集合.htm");
d.add("70","0","Gradle之恋－Init插件","my_data/Gradle之恋－Init插件.htm");
d.add("71","0","利用gradle shadowjar构建包含依赖的JAR包","my_data/利用gradle shadowjar构建包含依赖的JAR包.html");
document.write(d);
//-->
