d = new dTree("d");
<!--
d.add("0","-1","Hadoop资料","");
d.add("1","0","Hadoop2.2.0集群的HA高可靠的最简单配置","my_data/Hadoop2.2.0集群的HA高可靠的最简单配置/Hadoop2.2.0集群的HA高可靠的最简单配置.htm");
d.add("2","0","hadoop2.2.0集群的MapReduce的最简单配","my_data/Hadoop2.2.0集群的MapReduce的最简单配置.htm");
d.add("3","0","Hadoop2.x完整安装配置","my_data/Hadoop2.x完整安装配置/Hadoop2.x完整安装配置.htm");
d.add("4","0","hadoop2中ResourceManager的HA","my_data/hadoop2中ResourceManager的HA/hadoop2中ResourceManager的HA.htm");
d.add("5","0","hadoop2.0 HDFS搭建和HA切换","my_data/_hadoop2.0_HDFS搭建和HA切换.htm");
d.add("6","0","HDFS高可用方案之QJM","my_data/HDFS高可用方案之QJM.htm");
d.add("7","0","Hadoop管理员的十个最佳实践","my_data/Hadoop管理员的十个最佳实践.htm");
d.add("8","0","选择Cloudera CDH部署你的Cluster","my_data/选择Cloudera_CDH部署你的Cluster.htm");
d.add("9","0","使用yum安装CDH Hadoop集群","my_data/使用yum安装CDH Hadoop集群.htm");
d.add("10","0","Hadoop CDH四种安装方式总结及实例指导","my_data/Hadoop CDH四种安装方式总结及实例指导/index.html");
d.add("11","0","hadoop cdh 安装笔记","my_data/hadoop cdh 安装笔记/index.html");
d.add("12","0","卸载 Cloudera Manager 5.1.x.和 相关软件【官网翻译：高可用】","my_data/卸载_Cloudera_Manager_5.1.x.和_相关软件【官网翻译：高可用】_.htm");
d.add("13","0","cloudera(CDH)官网介绍：安装包、离线包该如何下载、官方文档等介绍","my_data/cloudera(CDH)官网介绍：安装包、离线包该如何下载、官方文档等介绍/index.html");
d.add("14","0","hadoop socket超时导致put失败解决方案","my_data/hadoop_socket超时导致put失败解决方案.htm");
d.add("15","0","Hadoop常见问题及解决办法","my_data/Hadoop常见问题及解决办法.htm");
d.add("16","0","将本地文件目录移动（或cp）到hdfs下shell脚本","my_data/将本地文件目录移动（或cp）到hdfs下shell脚本.htm");
d.add("17","0","如何进行单元测试","my_data/如何进行单元测试.htm");
d.add("18","0","Hadoop客户端该如何配置","my_data/Hadoop客户端该如何配置.htm");
d.add("19","0","MapReduce","");
d.add("20","19","Hadoop1 MapReduce 编写例子","my_data/MapReduce/Hadoop1 MapReduce 编写例子.htm");
d.add("21","19","Hadoop2 Mapreduce实例WordCount体验","my_data/MapReduce/Hadoop2 Mapreduce实例WordCount体验.htm");
d.add("22","19","从hadoop2.2，HBase0.96 mapreduce操作","my_data/MapReduce/从hadoop2.2，HBase0.96_mapreduce操作.htm");
d.add("23","19","Hadoop2.2.0 mapreduce 例子","my_data/MapReduce/Hadoop2.2.0_mapreduce_例子.htm");
d.add("24","19","多个MapReduce任务实现任务间相互依赖","my_data/MapReduce/多个MapReduce任务实现任务间相互依赖.htm");
d.add("25","19","Hadoop多用户资源管理–Fair Scheduler介绍与配置","my_data/MapReduce/Hadoop多用户资源管理–Fair Scheduler介绍与配置.htm");
document.write(d);
//-->
