d = new dTree("d");
<!--
d.add("0","-1","WJW Blog","");
d.add("1","0","笔记","");
d.add("2","1","程序员的十层楼","my_data/笔记/程序员的十层楼.htm");
d.add("3","1","停车入位","my_data/笔记/停车入位.html");
d.add("4","1","电脑键盘上你所不知道的秘密","my_data/笔记/电脑键盘上你所不知道的秘密.html");
d.add("5","1","Linux截图工具","my_data/笔记/Linux截图工具.md.html");
d.add("6","1","SSH使用公钥登陆","my_data/笔记/SSH使用公钥登陆.md.html");
d.add("7","1","Linux下怀疑被黑解决办法","my_data/笔记/Linux下怀疑被黑解决办法.htm");
d.add("8","1","如何优雅而科学地上外网","my_data/笔记/如何优雅而科学地上外网.htm");
d.add("9","1","高效的MacBook工作环境配置","my_data/笔记/高效的MacBook工作环境配置.htm");
d.add("10","1","常用的MarkDown语法","my_data/笔记/常用的MarkDown语法.html");
d.add("11","1","Mac_OS_X_JDK_环境变量配置","my_data/笔记/Mac_OS_X_JDK_环境变量配置.htm");
d.add("12","1","Mac无法通过smb连接到windows的共享文件夹","my_data/笔记/Mac无法通过smb连接到windows的共享文件夹.htm");
d.add("13","1","【Mac技术组】Compressor 4.1.x 使用教程","my_data/笔记/【Mac技术组】Compressor 4.1.x 使用教程/index.html");
d.add("14","1","LibreOffice 中的六大实用扩展组件","my_data/笔记/LibreOffice_中的六大实用扩展组件.htm");
d.add("15","1","如何摆脱项目命名困难的尴尬局面","my_data/笔记/如何摆脱项目命名困难的尴尬局面.htm");
d.add("16","0","开发","");
d.add("17","16","Java_GC日志","my_data/开发/Java_GC日志.html");
d.add("18","16","代码优化","my_data/开发/代码优化.htm");
d.add("19","16","Java语言学校的危险性（译文）","my_data/开发/Java语言学校的危险性（译文）.md.html");
d.add("20","16","为什么Lisp语言如此先进？","my_data/开发/为什么Lisp语言如此先进？.md.html");
d.add("21","16","URL的井号","my_data/开发/URL的井号.html");
d.add("22","16","JavaScript","");
d.add("23","22","JavaScript This 的六道坎","my_data/开发/JavaScript/JavaScript_This_的六道坎.htm");
d.add("24","22","JavaScript 中的 this","my_data/开发/JavaScript/JavaScript_中的_this.htm");
d.add("25","22","Zip 压缩、解压技术在 HTML5 浏览器中的应用","my_data/开发/JavaScript/Zip 压缩、解压技术在 HTML5 浏览器中的应用.htm");
d.add("26","22","两种方法判断是否为移动端访问，跳转到对应wap页面","my_data/开发/JavaScript/两种方法判断是否为移动端访问，跳转到对应wap页面.md.html");
d.add("27","22","Javascrip将html转成pdf","my_data/开发/JavaScript/Javascrip将html转成pdf.htm");
d.add("28","22","关于 Web Workers 你需要了解的 7 件事","my_data/开发/JavaScript/关于_Web_Workers_你需要了解的_7_件事.htm");
d.add("29","22","Js base64编码实现","my_data/开发/JavaScript/Js base64编码实现.html");
d.add("30","0","算法","");
d.add("31","30","GPG入门教程","my_data/算法/GPG入门教程.md.html");
d.add("32","30","有趣的二进制—高效位运算","my_data/算法/有趣的二进制—高效位运算/index.html");
d.add("33","0","杂谈","");
d.add("34","33","程序员精神崩溃怎么办？九大建议巧应对","my_data/杂谈/程序员精神崩溃怎么办？九大建议巧应对.md.html");
d.add("35","33","我为什么喜欢编程","my_data/杂谈/我为什么喜欢编程.md.html");
d.add("36","33","优秀的程序员如何思考、学习新技术的原则和方式","my_data/杂谈/优秀的程序员如何思考、学习新技术的原则和方式.htm");
d.add("37","33","为什么好多公司要费劲_DIY_私有云，而不是愉快地采用公有云？","my_data/杂谈/为什么好多公司要费劲_DIY_私有云，而不是愉快地采用公有云？.htm");
d.add("38","33","函数编程之道","my_data/杂谈/函数编程之道.md.html");
d.add("39","33","函数式编程另类指南","my_data/杂谈/函数式编程另类指南.htm");
d.add("40","0","安装指南","");
d.add("41","40","Ambari","");
d.add("42","41","(WJW)Ambari安装指南","my_data/安装指南/Ambari/(WJW)Ambari安装指南.md.html");
d.add("43","41","(WJW)Ambari在离线环境中安装Hadoop集群","my_data/安装指南/Ambari/(WJW)Ambari在离线环境中安装Hadoop集群.md.html");
d.add("44","40","Docker","");
d.add("45","44","(WJW)Docker安装笔记","my_data/安装指南/Docker/(WJW)Docker安装笔记.md.html");
d.add("46","44","(WJW)Docker私有Registry_V1在CentOS6_X下安装指南","my_data/安装指南/Docker/(WJW)Docker私有Registry_V1在CentOS6_X下安装指南.md.html");
d.add("47","44","(WJW)构建企业级Docker_Registry_V2","my_data/安装指南/Docker/(WJW)构建企业级Docker_Registry_V2.md.html");
d.add("48","40","Hadoop","");
d.add("49","48","(WJW)完全分布式Hadoop集群安装指南","my_data/安装指南/Hadoop/(WJW)完全分布式Hadoop集群安装指南.md.html");
d.add("50","40","HBase","");
d.add("51","50","(WJW)完全分布式HBase集群安装指南","my_data/安装指南/HBase/(WJW)完全分布式HBase集群安装指南.md.html");
d.add("52","40","Java","");
d.add("53","52","JMeter技巧","my_data/安装指南/Java/JMeter技巧.md.html");
d.add("54","40","Linux","");
d.add("55","54","CentOS 6.2 双网卡绑定单个IP地址","my_data/安装指南/Linux/!!!CentOS 6.2 双网卡绑定单个IP地址.md.html");
d.add("56","40","Memcached","");
d.add("57","56","(WJW)安装Memcached","my_data/安装指南/Memcached/(WJW)安装Memcached.md.html");
d.add("58","56","(WJW)Memcached高可用安装笔记","my_data/安装指南/Memcached/(WJW)Memcached高可用安装笔记.md.html");
d.add("59","56","定时检测Memcached进程是否存在,若不存在自动启动它","my_data/安装指南/Memcached/定时检测Memcached进程是否存在,若不存在自动启动它.md.html");
d.add("60","40","Redis","");
d.add("61","60","(WJW)Redis高可用安装笔记","my_data/安装指南/Redis/(WJW)Redis高可用安装笔记.md.html");
d.add("62","40","Tomcat","");
d.add("63","62","(WJW)Resin_to_Tomcat转换手册(JSP静态映射版)","my_data/安装指南/Tomcat/(WJW)Resin_to_Tomcat转换手册(JSP静态映射版).md.html");
d.add("64","62","(WJW)Resin_to_Tomcat转换手册(启动时编译版)","my_data/安装指南/Tomcat/(WJW)Resin_to_Tomcat转换手册(启动时编译版).md.html");
d.add("65","62","Tomcat/(WJW)tomcat7安装文档","my_data/安装指南/Tomcat/(WJW)tomcat7安装文档.md.html");
d.add("66","40","Galera_Cluster_For_MySQL","");
d.add("67","66","Galera_Cluster_For_MySQL集群安装","my_data/安装指南/Galera_Cluster_For_MySQL/Galera_Cluster_For_MySQL集群安装.md.html");
d.add("68","0","参考资料","");
d.add("69","68","Linux资料","../Linux/index.html","","(view_linux)");
d.add("70","68","Java资料","../java/index.html","","(view_java)");
d.add("71","68","Groovy指南","../Groovy/index.html","","(view_Groovy)");
d.add("72","68","Redis指令大全","../redis/index.html","","(view_redis)");
d.add("73","68","Git中文指南","../gitpro/index.html","","(view_git)");
d.add("74","68","Hadoop资料","../Hadoop/index.html","","(view_hadoop)");
d.add("75","68","HBase资料","../HBase/index.html","","(view_hbase)");
d.add("76","68","Gradle资料","../Gradle/index.html","","(view_gradle)");
document.write(d);
//-->
