(function(){var f=true,h=null,j=false,l=this,aa=function(a,b,c){a=a.split(".");c=c||l;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)if(!a.length&&b!==undefined)c[d]=b;else c=c[d]?c[d]:c[d]={}},ca=function(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array||!(a instanceof Object)&&Object.prototype.toString.call(a)=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";
if(!(a instanceof Object)&&(Object.prototype.toString.call(a)=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call")))return"function"}else return"null";else if(b=="function"&&typeof a.call=="undefined")return"object";return b};Math.floor(Math.random()*2147483648).toString(36);
var m=function(a,b){var c=b||l;if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(c,e)}}else return function(){return a.apply(c,arguments)}},o=function(a,b,c){aa(a,b,c)},p=function(a,b,c){a[b]=c},q=function(a,b){function c(){}c.prototype=b.prototype;a.Ba=b.prototype;a.prototype=new c};var r=function(a,b){var c=parseFloat(a);return isNaN(c)||c>1||c<0?b:c},da=function(a,b){if(a=="true")return f;if(a=="false")return j;return b},ea=/^([\w-]+\.)*([\w-]{2,})(\:[0-9]+)?$/,s=function(a,b){if(!a)return b;var c=a.match(ea);return c?c[0]:b};var fa=function(){return s("","pagead2.googlesyndication.com")};var ia=function(a){if(a.indexOf("&")!=-1)return"document"in l&&a.indexOf("<")==-1?ga(a):ha(a);return a},ga=function(a){var b=l.document.createElement("a");b.innerHTML=a;b.normalize&&b.normalize();a=b.firstChild.nodeValue;b.innerHTML="";return a},ha=function(a){return a.replace(/&([^;]+);/g,function(b,c){switch(c){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:if(c.charAt(0)=="#"){var d=Number("0"+c.substr(1));if(!isNaN(d))return String.fromCharCode(d)}return b}})},
ka=function(a,b){for(var c=0,d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=String(b).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),g=Math.max(d.length,e.length),i=0;c==0&&i<g;i++){var k=d[i]||"",n=e[i]||"",G=RegExp("(\\d*)(\\D*)","g"),y=RegExp("(\\d*)(\\D*)","g");do{var A=G.exec(k)||["","",""],B=y.exec(n)||["","",""];if(A[0].length==0&&B[0].length==0)break;c=A[1].length==0?0:parseInt(A[1],10);var ba=B[1].length==0?0:parseInt(B[1],10);c=ja(c,ba)||ja(A[2].length==0,B[2].length==0)||
ja(A[2],B[2])}while(c==0)}return c},ja=function(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};var t=function(a,b){this.width=a;this.height=b};t.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};t.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};var u,la,ma,na,oa,pa=function(){return l.navigator?l.navigator.userAgent:h},qa=function(){oa=na=ma=la=u=j;var a;if(a=pa()){var b=l.navigator;u=a.indexOf("Opera")==0;la=!u&&a.indexOf("MSIE")!=-1;na=(ma=!u&&a.indexOf("WebKit")!=-1)&&a.indexOf("Mobile")!=-1;oa=!u&&!ma&&b.product=="Gecko"}};qa();
var ra=u,sa=la,ta=oa,ua=ma,va=na,xa=function(){var a="",b;if(ra&&l.opera){a=l.opera.version;a=typeof a=="function"?a():a}else{if(ta)b=/rv\:([^\);]+)(\)|;)/;else if(sa)b=/MSIE\s+([^\);]+)(\)|;)/;else if(ua)b=/WebKit\/(\S+)/;if(b)a=(a=b.exec(pa()))?a[1]:""}if(sa){b=wa();if(b>parseFloat(a))return String(b)}return a},wa=function(){var a=l.document;return a?a.documentMode:undefined},ya=xa(),za={},Aa=function(a){return za[a]||(za[a]=ka(ya,a)>=0)};!sa||Aa("9");sa&&Aa("9");var Ba=function(a){var b=a.document;if(ua&&!Aa("500")&&!va){if(typeof a.innerHeight=="undefined")a=window;b=a.innerHeight;var c=a.document.documentElement.scrollHeight;if(a==a.top)if(c<b)b-=15;return new t(a.innerWidth,b)}a=b.compatMode=="CSS1Compat";if(ra&&!Aa("9.50"))a=j;a=a?b.documentElement:b.body;return new t(a.clientWidth,a.clientHeight)};var v=document,w=window,Ca=function(a){var b=h;if((a=a.getElementsByTagName("script"))&&a.length){b=a[a.length-1];b=b.parentNode}return b};Ca(v);var Da="http://"+fa()+"/pagead/show_ads.js";function x(a){return typeof encodeURIComponent=="function"?encodeURIComponent(a):escape(a)}function Ea(a,b,c){var d=document.createElement("script");d.type="text/javascript";if(b)d.onload=b;if(c)d.id=c;d.src=a;var e=document.getElementsByTagName("head")[0];if(!e)return j;window.setTimeout(function(){e.appendChild(d)},0);return f}
function Fa(a,b){if(a.attachEvent){a.attachEvent("onload",b);return f}if(a.addEventListener){a.addEventListener("load",b,j);return f}return j}var Ga=function(a){if(!("google_onload_fired"in a)){a.google_onload_fired=j;Fa(a,function(){a.google_onload_fired=f})}};function Ha(a,b){a.google_image_requests||(a.google_image_requests=[]);var c=new Image;c.src=b;a.google_image_requests.push(c)}function Ia(a){if(a in Ja)return Ja[a];return Ja[a]=navigator.userAgent.toLowerCase().indexOf(a)!=-1}var Ja={};
function Ka(){if(navigator.plugins&&navigator.mimeTypes.length){var a=navigator.plugins["Shockwave Flash"];if(a&&a.description)return a.description.replace(/([a-zA-Z]|\s)+/,"").replace(/(\s)+r/,".")}else if(navigator.userAgent&&navigator.userAgent.indexOf("Windows CE")>=0){a=3;for(var b=1;b;)try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+(a+1));a++}catch(c){b=h}return a.toString()}else if(Ia("msie")&&!window.opera){b=h;try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(d){a=
0;try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");a=6;b.AllowScriptAccess="always"}catch(e){if(a==6)return a.toString()}try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(g){}}if(b){a=b.GetVariable("$version").split(" ")[1];return a.replace(/,/g,".")}}return"0"}function La(a,b){if(!(Math.random()<1.0E-4)){var c=Math.random();if(c<b){c=Math.floor(c/b*a.length);return a[c]}}return""}
var Ma=function(a){a.u_tz=-(new Date).getTimezoneOffset();a.u_his=window.history.length;a.u_java=navigator.javaEnabled();if(window.screen){a.u_h=window.screen.height;a.u_w=window.screen.width;a.u_ah=window.screen.availHeight;a.u_aw=window.screen.availWidth;a.u_cd=window.screen.colorDepth}if(navigator.plugins)a.u_nplug=navigator.plugins.length;if(navigator.mimeTypes)a.u_nmime=navigator.mimeTypes.length},Na=function(a,b){var c=b||w;if(a&&c.top!=c)c=c.top;try{return c.document&&!c.document.body?new t(-1,
-1):Ba(c||window)}catch(d){return new t(-12245933,-12245933)}},Oa=function(a,b){var c=a.length;if(c==0)return 0;for(var d=b||305419896,e=0;e<c;e++){var g=a.charCodeAt(e);d^=(d<<5)+(d>>2)+g&4294967295}return d>0?d:4294967296+d},Pa=function(a){if(a==a.top)return 0;var b=[];b.push(a.document.URL);a.name&&b.push(a.name);var c=f;a=Na(!c,a);b.push(a.width.toString());b.push(a.height.toString());return Oa(b.join(""))},Qa=function(a){if(!a)return"";var b=[],c=0;for(a=a;a&&c<25;a=a.parentNode,++c)b.push(a.id||
"");return b.join()},Ra=function(a){try{return!!a.document}catch(b){return j}};var Sa=r("0.005",0),Ta=r("0.01",0),Ua=r("0.001",0),Va=r("0.012",0),Wa=r("0.012",0);var Xa=da("false",j),Ya=da("false",j),Za=da("false",j),$a=da("false",j);var ab=function(a,b,c){b=m(b,l,a);a=window.onerror;window.onerror=b;try{c()}catch(d){c=d.toString();var e="";if(d.fileName)e=d.fileName;var g=-1;if(d.lineNumber)g=d.lineNumber;b=b(c,e,g);if(!b)throw d;}window.onerror=a};o("google_protectAndRun",ab);
var cb=function(a,b,c,d){if(Math.random()<0.01){var e=v;a=["http://",s("","pagead2.googlesyndication.com"),"/pagead/gen_204","?id=jserror","&jscb=",Xa?1:0,"&jscd=",Ya?1:0,"&context=",x(a),"&msg=",x(b),"&file=",x(c),"&line=",x(d.toString()),"&url=",x(e.URL.substring(0,512)),"&ref=",x(e.referrer.substring(0,512))];a.push(bb());Ha(w,a.join(""))}return!Za};o("google_handleError",cb);
var bb=function(){var a=["&client=",x(w.google_ad_client),"&format=",x(w.google_ad_format),"&slotname=",x(w.google_ad_slot),"&output=",x(w.google_ad_output),"&ad_type=",x(w.google_ad_type)];return a.join("")};var z=function(a){this.M=[];this.R=a||window;this.o=0;this.L=h},db=function(a,b){this.fn=a;this.win=b};z.prototype.enqueue=function(a,b){if(this.o==0&&this.M.length==0&&(!b||b==window)){this.o=2;this.ba(new db(a,window))}else{this.M.push(new db(a,b||this.R));eb(this)}};z.prototype.aa=function(a){this.o=1;if(a)this.L=this.R.setTimeout(m(this.N,this),a)};z.prototype.N=function(){if(this.o==1){if(this.L!=h){this.R.clearTimeout(this.L);this.L=h}this.o=0}eb(this)};z.prototype.statusz=function(){return f};
p(z.prototype,"nq",z.prototype.enqueue);p(z.prototype,"al",z.prototype.aa);p(z.prototype,"rl",z.prototype.N);p(z.prototype,"sz",z.prototype.statusz);var eb=function(a){a.R.setTimeout(m(a.qa,a),0)};z.prototype.qa=function(){if(this.o==0&&this.M.length){var a=this.M.shift();this.o=2;a.win.setTimeout(m(this.ba,this,a),0);eb(this)}};z.prototype.ba=function(a){this.o=0;a.fn()};var fb=!!window.google_async_iframe_id,C=fb&&window.parent||window,gb=function(){if(fb&&!Ra(C)){for(var a="."+v.domain;a.split(".").length>2&&!Ra(C);){v.domain=a=a.substr(a.indexOf(".")+1);C=window.parent}Ra(C)||(C=window)}return C};var D=function(a){this.B=a;this.Z=[];this.Y=0;this.H=[];this.ka=0;this.Q=[];this.ja=j;this.g=this.ga="";this.ia=j},hb=function(a,b,c){var d=a.B[c],e=a.Z;a.B[c]=function(g){if(g&&g.length>0){var i=g.length>1?g[1].url:h;e.push([b,ia(g[0].url),i])}d(g)}},ib=function(a){a.Y++},jb=function(a,b){a.H.push(b)},kb="http://"+fa()+"/pagead/osd.js",lb=function(a){if(!a.ja){Ga(gb());Ea(kb);a.ja=f}},mb=function(a,b){if(a.Y>0)for(var c=a.B.document.getElementsByTagName("iframe"),d=a.ia?"google_ads_iframe_":"google_ads_frame",
e=0;e<c.length;e++){var g=c.item(e);g.src&&g.name&&g.name.indexOf(d)==0&&b(g,g.src)}},nb=function(a,b){var c=a.Z;if(c.length>0)for(var d=a.B.document.getElementsByTagName("a"),e=0;e<d.length;e++)for(var g=0;g<c.length;g++)if(d.item(e).href==c[g][1]){var i=d.item(e).parentNode;if(c[g][2])for(var k=i,n=0;n<4;n++){if(k.innerHTML.indexOf(c[g][2])>0){i=k;break}k=k.parentNode}b(i,c[g][0]);c.splice(g,1);break}},pb=function(a,b){for(var c=0;c<a.H.length;c++){var d=a.H[c],e=ob(d);if(e)(e=a.B.document.getElementById("google_ads_div_"+
e))&&b(e,d)}};D.prototype.W=function(a){nb(this,a);pb(this,a);mb(this,a)};D.prototype.setupOsd=function(a,b,c){this.ka=a;this.ga=b;this.g=c};D.prototype.getOsdMode=function(){return this.ka};D.prototype.getEid=function(){return this.ga};D.prototype.getCorrelator=function(){return this.g};D.prototype.X=function(){return this.Z.length+this.Y+this.H.length};D.prototype.setValidOutputTypes=function(a){this.Q=a};
D.prototype.registerAdBlockByType=function(a,b,c){if(this.Q.length>0){for(var d=0;d<this.Q.length;d++)if(this.Q[d]==a){this.ia=c;if(a=="js")hb(this,b,"google_ad_request_done");else if(a=="html")ib(this);else a=="json_html"&&jb(this,b)}lb(this)}};var ob=function(a){if((a=a.match(/[&\?](?:slotname)=([^&]+)/))&&a.length==2)return a[1];return""},qb=function(){var a=gb();a.__google_ad_urls||(a.__google_ad_urls=new D(a));return a.__google_ad_urls};o("Goog_AdSense_getAdAdapterInstance",qb);
o("Goog_AdSense_OsdAdapter",D);o("Goog_AdSense_OsdAdapter.prototype.numBlocks",D.prototype.X);o("Goog_AdSense_OsdAdapter.prototype.findBlocks",D.prototype.W);o("Goog_AdSense_OsdAdapter.prototype.getOsdMode",D.prototype.getOsdMode);o("Goog_AdSense_OsdAdapter.prototype.getEid",D.prototype.getEid);o("Goog_AdSense_OsdAdapter.prototype.getCorrelator",D.prototype.getCorrelator);o("Goog_AdSense_OsdAdapter.prototype.setValidOutputTypes",D.prototype.setValidOutputTypes);
o("Goog_AdSense_OsdAdapter.prototype.setupOsd",D.prototype.setupOsd);o("Goog_AdSense_OsdAdapter.prototype.registerAdBlockByType",D.prototype.registerAdBlockByType);var rb={google_ad_channel:"channel",google_ad_host:"host",google_ad_host_channel:"h_ch",google_ad_host_tier_id:"ht_id",google_ad_section:"region",google_ad_type:"ad_type",google_adtest:"adtest",google_allow_expandable_ads:"ea",google_alternate_ad_url:"alternate_ad_url",google_alternate_color:"alt_color",google_bid:"bid",google_city:"gcs",google_color_bg:"color_bg",google_color_border:"color_border",google_color_line:"color_line",google_color_link:"color_link",google_color_text:"color_text",google_color_url:"color_url",
google_contents:"contents",google_country:"gl",google_cpm:"cpm",google_cust_age:"cust_age",google_cust_ch:"cust_ch",google_cust_gender:"cust_gender",google_cust_id:"cust_id",google_cust_interests:"cust_interests",google_cust_job:"cust_job",google_cust_l:"cust_l",google_cust_lh:"cust_lh",google_cust_u_url:"cust_u_url",google_disable_video_autoplay:"disable_video_autoplay",google_ed:"ed",google_encoding:"oe",google_feedback:"feedback_link",google_flash_version:"flash",google_font_face:"f",google_font_size:"fs",
google_hints:"hints",google_kw:"kw",google_kw_type:"kw_type",google_language:"hl",google_page_url:"url",google_region:"gr",google_reuse_colors:"reuse_colors",google_safe:"adsafe",google_tag_info:"gut",google_targeting:"targeting",google_targeting_video_doc_id:"tvdi",google_ui_features:"ui",google_ui_version:"uiv",google_video_doc_id:"video_doc_id",google_video_product_type:"video_product_type"},sb={google_ad_block:"ad_block",google_ad_client:"client",google_ad_format:"format",google_ad_output:"output",
google_ad_callback:"callback",google_ad_height:"h",google_ad_override:"google_ad_override",google_ad_slot:"slotname",google_ad_width:"w",google_ctr_threshold:"ctr_t",google_image_size:"image_size",google_last_modified_time:"lmt",google_max_num_ads:"num_ads",google_max_radlink_len:"max_radlink_len",google_num_radlinks:"num_radlinks",google_num_radlinks_per_unit:"num_radlinks_per_unit",google_only_ads_with_video:"only_ads_with_video",google_rl_dest_url:"rl_dest_url",google_rl_filtering:"rl_filtering",
google_rl_mode:"rl_mode",google_rt:"rt",google_skip:"skip"},tb={google_only_pyv_ads:"pyv",google_with_pyv_ads:"withpyv"};var E=document,F=navigator,H=window;
function ub(){var a=E.cookie,b=Math.round((new Date).getTime()/1E3),c=H.google_analytics_domain_name;c=typeof c=="undefined"?vb("auto"):vb(c);var d=a.indexOf("__utma="+c+".")>-1,e=a.indexOf("__utmb="+c)>-1,g=a.indexOf("__utmc="+c)>-1,i={},k=!!H&&!!H.gaGlobal;if(d){a=a.split("__utma="+c+".")[1].split(";")[0].split(".");i.sid=e&&g?a[3]+"":k&&H.gaGlobal.sid?H.gaGlobal.sid:b+"";i.vid=a[0]+"."+a[1];i.from_cookie=f}else{i.sid=k&&H.gaGlobal.sid?H.gaGlobal.sid:b+"";i.vid=k&&H.gaGlobal.vid?H.gaGlobal.vid:
(Math.round(Math.random()*2147483647)^wb()&2147483647)+"."+b;i.from_cookie=j}i.dh=c;i.hid=k&&H.gaGlobal.hid?H.gaGlobal.hid:Math.round(Math.random()*2147483647);return H.gaGlobal=i}
function wb(){var a=E.cookie?E.cookie:"",b=H.history.length,c,d=[F.appName,F.version,F.language?F.language:F.browserLanguage,F.platform,F.userAgent,F.javaEnabled()?1:0].join("");if(H.screen)d+=H.screen.width+"x"+H.screen.height+H.screen.colorDepth;else if(H.java){c=java.awt.Toolkit.getDefaultToolkit().getScreenSize();d+=c.screen.width+"x"+c.screen.height}d+=a;d+=E.referrer?E.referrer:"";for(a=d.length;b>0;)d+=b--^a++;return xb(d)}
function xb(a){var b=1,c=0,d;if(!(a==undefined||a=="")){b=0;for(d=a.length-1;d>=0;d--){c=a.charCodeAt(d);b=(b<<6&268435455)+c+(c<<14);c=b&266338304;b=c!=0?b^c>>21:b}}return b}function vb(a){if(!a||a==""||a=="none")return 1;if("auto"==a){a=E.domain;if("www."==a.substring(0,4))a=a.substring(4,a.length)}return xb(a.toLowerCase())};function yb(a,b,c,d){this._value_=a;this._expires_=b;this._path_=c;this._domain_=d;if(!this._path_)this._path_="/";if(this._domain_==h)this._domain_=document.domain}yb.prototype.toString=function(){return"[GA_GoogleCookieInfo: value="+this._value_+", expires="+this._expires_+", path="+this._path_+"]"};function I(){this.v=zb(this);this.T=j;if(!this.v)this.T=Ab(this)}I.prototype.S="__gads=";I.prototype.C="GoogleAdServingTest=";I.prototype.O=function(a){this.q=a._cookies_[0];if(this.q!=h){this.v=this.q._value_;Bb(this)}};p(I.prototype,"setCookieInfo",I.prototype.O);
var Cb=function(a,b){var c=(new Date).valueOf(),d=new Date;d.setTime(c+b);return d},Db=function(a){var b=15552E6;a=Cb(a,b);b="ID=12345:T="+b;var c="/",d=document.domain;return new yb(b,a.valueOf(),c,d)},Eb="http://"+s("","partner.googleadservices.com")+"/gampad/cookie.js?callback=_GA_googleCookieHelper.setCookieInfo",Fb=function(a,b){if(!(a.v||!a.T)){var c="script",d=document.domain;d=Eb+"&client="+x(b)+"&domain="+x(d);document.write("<"+c+' src="'+d+'"></'+c+">")}},Ab=function(a){document.cookie=
a.C+"Good";var b=Gb(a,a.C);if(b=b=="Good"){var c=Cb(a,-1);document.cookie=a.C+"; expires="+c.toGMTString()}return b},zb=function(a){return a=Gb(a,a.S)},Gb=function(a,b){var c=document.cookie,d=c.indexOf(b),e="";if(d!=-1){d=d+b.length;e=c.indexOf(";",d);if(e==-1)e=c.length;e=c.substring(d,e)}return e},Bb=function(a){if(a.q!=h)if(a.v){var b=new Date;b.setTime(1E3*a.q._expires_);var c=a.q._domain_;a=a.S+a.v+"; expires="+b.toGMTString()+"; path="+a.q._path_+"; domain=."+c;document.cookie=a}};function Hb(a,b){try{return a.top.document==b}catch(c){}return j};var Ib=function(a){var b="google_unique_id";if(a[b])++a[b];else a[b]=1;return a[b]};var Jb=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([\\w\\d\\-\\u0100-\\uffff.%]*)(?::([0-9]+))?)?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$"),Kb=function(a){return a&&decodeURIComponent(a)};var Lb=function(a){this.pa=(this.U=a&&a.GA_jstiming)&&this.U.load};Lb.prototype.tick=function(a,b){this.pa.tick(a,b)};Lb.prototype.report=function(a){var b={};b.e=a;this.U.report(this.pa,b)};var Mb=function(){};q(Mb,Lb);Mb.prototype.tick=function(){};Mb.prototype.report=function(){};var Nb=function(a,b,c,d){if(c<=4){b=b+"_"+c;d?a.tick(b,d+"_"+c):a.tick(b)}};var Ob=function(a,b){var c=0,d=[];a&&d.push(a);if(b){var e=Qa(b);e&&d.push(e)}if(d.length>0)c=Oa(d.join(":"));return c.toString()};var J=w&&Math.random()<Sa&&w.GA_jstiming&&w.GA_jstiming.load&&w.location.protocol=="http:"?new Lb(w):new Mb(w);J.tick("js_load");function K(a){return typeof a=="function"}function Pb(a,b){if(typeof a!="string"||a.length==0)return h;else if(typeof b!="string"||b.length==0)return h;return Qb(L(),a,b)}o("GA_googleAddSlot",Pb);function _GA_googleInitializeAdEngine(a){if(!M()){Rb(Sb(a));Tb(M())}}o("_GA_googleInitializeAdEngine",_GA_googleInitializeAdEngine);
function Ub(){L().ra=f;_GA_googleInitializeAdEngine(h);var a=M().h;a=="sync"||a=="sync_sra"?M().m():Vb(L())}o("GA_googleFetchAds",Ub);function Wb(){_GA_googleInitializeAdEngine("iframe");Fb(window._GA_googleCookieHelper,window.GS_googleGetIdsForAdSenseService())}o("GA_googleUseIframeRendering",Wb);function Xb(){var a=window.GA_googleEnv.getParameter("google_ad_impl");a==h&&window.GA_googleEnv.setParameter("google_ad_impl","sync_sra")}o("GA_googleUseSyncSRARendering",Xb);
function Yb(a){window.GA_googleEnv.setParameter("google_domain_reset_url",a)}o("GA_googleDomainResetUrl",Yb);function Zb(a){var b=Ca(v);$b(L(),a,b);if(M()!=h)if(M().h!="iframe"){if(ac(M()))if(M().P){b=N(L(),a);if(b==h)return;else if(!b._enabled_)return}else return;else if(O(M(),a)!=h&&!M().k)return;M().p(a)}}o("GA_googleFillSlot",Zb);function bc(a,b,c,d){a=a||"";b=b||"";c=c||0;d=d||0;var e=Ca(v);$b(L(),b,e);if(M()!=h)if(M().h=="iframe"){Qb(L(),a,b);a=new cc(c,d,j,f);dc(L(),b,a);M().p(b)}}
o("GA_googleFillSlotWithSize",bc);function ec(){fc(new gc(rb));Rb(h)}o("GA_googleResetAll",ec);window.google_noFetch=j;function hc(){window.google_noFetch=f}o("GA_googleNoFetch",hc);function ic(){window.google_delayFetch=f}o("GA_googleDelayFetch",ic);function cc(a,b,c,d){this._width_=a;this._height_=b;this._expandable_=c;this._enabled_=d}
cc.prototype.toString=function(){return"[GA_GoogleAdSlotAttr: width="+this._width_+", height="+this._height_+", expandable="+this._expandable_+", enabled="+this._enabled_+"]"};function jc(a){var b={};a=a.split("?");a=a[a.length-1].split("&");for(var c=0;c<a.length;c++){var d=a[c].split("=");if(d[0])try{b[d[0].toLowerCase()]=d.length>1?window.decodeURIComponent?decodeURIComponent(d[1].replace(kc," ")):unescape(d[1]):""}catch(e){}}return b}function lc(a){a=a||document.URL;this.na=jc(a)}
lc.prototype.getParameter=function(a){return a==h?h:this.na[a]};lc.prototype.setParameter=function(a,b){this.na[a]=b};var mc=function(){if(!$a)return"http://"+s("","pubads.g.doubleclick.net");return"https://"+s("","securepubads.g.doubleclick.net")};function P(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;")}function nc(){this.F=h;this.oa=j;this.Aa=(new Date).valueOf()}
var pc=function(a,b){if(a.F==h)if(!a.oa){a.F=window.open("","GoogleAdCapture","width=1100, height=1400, status=no, resizable=yes, scrollbars=yes,menubar=yes, toolbar=yes");if(a.F){var c=a.F.document,d=[];d.push('<html>\n<head>\n<title>Google Ad Capture Window</title>\n<script>function displayTime(id, start){var delta=(new Date()).valueOf() - start;document.getElementById(id).innerHTML=""+delta;}var pageStartTime = (new Date()).valueOf();var slotStartTime = 0;window.onload=function(){displayTime("total", pageStartTime);};<\/script></head>\n<body>\n');
d.push("<p>Google Ad Capture Window</p>");for(var e in b)K(b[e])||d.push(oc(a,e,b[e]));d.push("<p>Time blocked rendering ads (ms): <label id='blocked'></label>");d.push("<script>displayTime('blocked', pageStartTime);<\/script>");d.push("<p>Total Page Load Time (ms): <label id='total'></label>");d.push("</body>\n</html>");d=d.join("\n");(e=window.GA_googleEnv.getParameter("google_capture_norender")!=h)?c.write(P(d)):c.write(d);c.close()}else a.oa=f}},oc=function(a,b,c){a="<script>slotStartTime = (new Date()).valueOf();<\/script>";
var d="<p>Slot "+b+"</p>";c=c==h||c._html_==h?"No ad":c._html_;var e="<p>Slot Time (ms): <label id='"+b+"'></label>";b='<script>displayTime("'+b+'", slotStartTime);<\/script>';return a+d+"\n"+c+"\n"+e+b};function qc(a){this.d={};this.D=a}var rc=function(a,b,c,d){if(b){c||(c="");if(b=="google_gl")b="google_country";else if(b=="google_region")b="google_section";if(b in a.D)if((d=typeof d=="undefined"||d)||!a.d[b])a.d[b]=c}},sc=function(a,b){for(var c in b.d)K(b.d[c])||a.d[c]||(a.d[c]=b.d[c])};
qc.prototype.getAttribute=function(a){return this.d[a]};qc.prototype.i=function(){var a=[];for(var b in this.d)if(!K(this.d[b])){var c=rb[b]||sb[b]||tb[b]||h,d=this.d[b];c&&d&&a.push(c+"="+x(d))}return a.join("&")};
var uc=function(a,b,c,d){a=tc(a,b,c,d);b=[];a[0]&&a[0].length>0&&b.push(a[0].join("&"));a[1]&&a[1].length>0&&b.push("sps="+a[1].join("|"));return b.join("&")},tc=function(a,b,c,d){var e=[],g=[];b=b.d;for(var i in d)if(!K(i)){var k=d[i];if(k){var n="";if(b[i]!=h)n=x(b[i]);var G=[],y=-1,A=-1;for(var B in a)if(!K(a[B])){++y;if(c[B]==h)G.push("");else{var ba=c[B].d;if(ba[i]!=h){G.push(x(x(ba[i])));A=y}else G.push("")}}if(A>=0){y=x(n);n=[];n.push(y);for(y=0;y<=A;++y)n.push(G[y]);g.push(k+","+n.join(","))}else n&&
e.push(k+"="+n)}}a=[];a.push(e);a.push(g);return a};function vc(a,b){this.K=a;this.t=b;this.ca=0;this.xa=this.V=this.$=j;this.va=this.wa=this.ha=this.sa=h}var wc=function(a){a.V=f;a.sa=(new Date).valueOf()},xc=function(a){a.ha=(new Date).valueOf()},yc=function(a){a.xa=f;a.wa=(new Date).valueOf()},zc=function(a){a.va=(new Date).valueOf()};vc.prototype.toString=function(){return"[GA_GoogleAdSlot: pubid="+this.K+", name="+this.t+", loaded="+this.$+", tries="+this.ca+"]"};
function gc(a){this.a={};this.c=[];this.s={};this.D=a;this.ma=new qc(this.D);this.A={};this.ra=j;this.l=h;this.ea={}}
var Qb=function(a,b,c){b=new vc(b,c);return a.a[b.t]=b},Ac=function(a,b){var c=[];for(var d in a.a)if(!K(a.a[d])){if(b){var e=N(a,d);if(e==h||!e._enabled_)continue}e=a.a[d];e.V||c.push(e)}return c},Bc=function(a,b){return Ac(a,b).length},Cc=function(a){var b=[];for(var c in a.a){var d=a.a[c];K(d)||d.V&&d.ha==h&&b.push(c)}return b},Dc=function(a){var b=0;for(var c in a.a)if(!K(a.a[c])){var d=N(a,c);d!=h&&d._enabled_&&b++}return b},Ec=function(a){for(var b in a.a)if(!K(a.a[b])){var c=a.a[b];wc(c)}},
Fc=function(a,b){var c=a.a[b];wc(c)},Gc=function(a,b){var c=a.a[b];xc(c)},Hc=function(a,b){var c=a.a[b];yc(c)},Q=function(a,b){var c=a.a[b];zc(c);Nb(J,"ga_render",a.c.length,"ga_srt")},Ic=function(a){var b=0;for(var c in a.a)K(a.a[c])||b++;return b};gc.prototype.toString=function(){var a="[AdData:",b=[];for(var c in this.a)K(this.a[c])||b.push(this.a[c].toString());for(var d in this.s)K(this.s[d])||b.push("["+d+","+this.s[d]+"]");a+=b.join();a+="]";return a};
var Jc=function(a,b){return a.a[b]},Kc=function(a,b,c){if(!(b==h||b.length==0)){if(c==h||c.length==0)c="";var d=a.s[b];a.s[b]=d==h?c:d+","+c}};function Lc(a,b){Kc(L(),a,b)}o("GA_googleAddAttr",Lc);var Mc=function(a,b,c){rc(a.ma,b,c)};function Nc(a,b){Mc(L(),a,b)}o("GA_googleAddAdSensePageAttr",Nc);var Oc=function(a){return a.ma},Pc=function(a,b,c,d){if(!(b==h||b.length==0)){if(M()==h||M().h!="iframe"){var e=a.a[b];if(e==h)return}e=a.A[b];if(e==h)a.A[b]=new qc(a.D);rc(a.A[b],c,d)}};
function Qc(a,b,c){Pc(L(),a,b,c)}o("GA_googleAddAdSenseSlotAttr",Qc);
var Rc=function(a,b){return a.A[b]},$b=function(a,b,c){a.ea[b]=c},Sc=function(a,b){return a.ea[b]},Tc=function(){var a=mc();return a+"/gampad/slotdata.js?callback=GA_googleSetAdSlotAttributes"},Vb=function(a){if(a.l!=h)M().m();else{var b=[];for(var c in a.a)K(a.a[c])||b.push(c);a=window.GS_googleGetIdsForAdSenseService();b=Tc(window)+"&client="+escape(a)+"&page_slots="+escape(b.join());document.write("<script src = '"+b+"'><\/script>")}},Uc=function(a,b){a.l=b;M().P=f;M().m()};
function Vc(a){Uc(L(),a)}o("GA_googleSetAdSlotAttributes",Vc);var dc=function(a,b,c){if(a.l==h)a.l={};a.l[b]=c;M().P=f},N=function(a,b){return a.l!=h?a.l[b]:h};function Wc(a,b,c){if(!c||c<0||c>1)c=0;this.ya=Math.random()<c;this.ta=a;this.da=b+"/pagead/gen_204?id="+x(a);this.ua=[]}
var R=function(a,b,c){if(b&&b.match(/^\w+$/)&&c)a.da+="&"+b+"="+x(c)},Xc=function(a){var b=L();for(var c in b.a){var d=b.a[c];if(!K(d)&&d.K!=h){R(a,"pub_id",d.K);break}}R(a,"nslots",Ic(b).toString());R(a,"pub_url",document.URL);R(a,"pub_ref",document.referrer)},Yc=function(a){if(!a.ya||!a.ta||!a.da)return j;var b=new Image;b.src=a.da;a.ua.push(b);return f};function S(a){this.f=h;this.l={};this.r=this.b="";this.k=a;this.j=this.J=this.z=j;this.h="sync";this.za=rb;this.u=f;this.fa=this.P=j}
var Tb=function(a){a.z=window.GA_googleEnv.getParameter("google_nofetch")!=h||window.google_noFetch;a.J=window.GA_googleEnv.getParameter("google_norender")!=h;a.j=window.GA_googleEnv.getParameter("google_capture")!=h||window.GA_googleEnv.getParameter("google_capture_norender")!=h;if(a.j)a.J=f;Zc(a,window);a.b=a.r;var b=m(a.la,a);$c(a,window,b)},ad=function(a){a.fa=f},$c=function(a,b,c){if(b.attachEvent){b.attachEvent("onload",c);return f}if(b.addEventListener){b.addEventListener("load",c,j);return f}return j};
S.prototype.G=function(){this.j&&pc(window.GA_googleAdCapture,this.f)};var bd=function(a){if(a.h=="sync_sra"){var b=L(),c=Ic(b);b=b.c.length;if(c!=b){a.I=new Wc("sra_mismatch",mc(),Ua);R(a.I,"correlator",a.g);R(a.I,"fslots",b.toString());Xc(a.I);Yc(a.I)}}},cd=function(a){J.tick("ga_onload");J.report(a.h)},dd=function(a){var b=Cc(L());if(b.length>0){a.w=new Wc("missing_cb",mc(),Ta);R(a.w,"pending",b.join());R(a.w,"correlator",a.g);R(a.w,"impl",a.h);Xc(a.w);Yc(a.w)}};
S.prototype.la=function(){cd(this);this.G();bd(this);dd(this)};var Zc=function(a){var b=window.GA_googleEnv.getParameter("google_ad_url");if(b==h||b.length==0)a.r=mc()+"/gampad/ads?";else{if(b.charAt(b.length-1)!="?")b+="?";a.r=b}};S.prototype.n=function(){};
var O=function(a,b){return a.f!=h?a.f[b]:h},ed=function(){var a=navigator.userAgent,b=a.indexOf("MSIE ");return b==-1?0:parseFloat(a.substring(b+5,a.indexOf(";",b)))},kc=/\+/g,fd=function(a,b){b=b.toLowerCase();if(b.substring(0,3)!="ca-")b="ca-"+b;return b},U=function(a,b,c){c!=h&&T(a,b,x(c.toString()))},T=function(a,b,c){if(c!=h&&c!="")a.b+=a.b.charAt(a.b.length-1)!="?"?"&"+b+"="+c:b+"="+c},gd=function(a,b){for(var c=Ac(L(),a.u),d=[],e=[],g=[],i=c.length,k=0;k<i;k++){var n=c[k];g.push(n.t);if(!(b!=
h&&b!=n.t)){d.push(n.t);e.push(fd(a,n.K))}}U(a,"client",e[0]);if(a.k)g.length>0&&U(a,"page_slots",g.join());else{U(a,"slotname",d.join());L().c.length>0&&U(a,"page_slots",L().c.join())}},hd=function(a,b,c){if(c!=h){a=b.lastIndexOf("?");a=b.indexOf("google_preview=",a);c=b.indexOf("&",a);if(c==-1){c=b.length-1;a-=1}return b.substring(0,a)+b.substring(c+1,b.length)}return b},id=function(a,b,c){if(Hb(b,c))return c.URL;return c.referrer},kd=function(a,b,c){if(jd(a,b,c)!=c.URL)return c.domain;return""},
jd=function(a,b,c){var d=Oc(L()).getAttribute("google_page_url");if(d)return d;return id(a,b,c)},ld=function(a,b,c,d){U(a,"url",hd(a,jd(a,window,document),window.GA_googleEnv.getParameter("google_preview")));U(a,"ref",document.referrer);U(a,"lmt",(Date.parse(document.lastModified)/1E3).toString());T(a,"dt",b.getTime());if(document.body){b=document.body.scrollHeight;var e=document.body.clientHeight;e&&b&&U(a,"cc",Math.round(e*100/b).toString())}b=f;if(b=Na(b)){U(a,"biw",b.width);U(a,"bih",b.height)}b=
Ib(window);U(a,"ifi",b);b=Pa(window);b!=0&&U(a,"ifk",b.toString());b=Ob(c,Sc(L(),c));U(a,"adk",b);b=window.GA_googleEnv.getParameter("deb");b!=h&&U(a,"deb",b);b=window.GA_googleEnv.getParameter("haonly");b!=h&&U(a,"haonly",b);b=Oc(L());navigator.userAgent.indexOf("MSIE ")>0&&rc(b,"google_encoding",document.charset,j);e="";if(d)e=uc(L().a,b,L().A,a.za);else{c=Rc(L(),c);if(c==h)c=b;else sc(c,b);e=c.i()}if(e)a.b+="&"+e},md=function(a,b,c){var d=L().s,e=[];for(var g in d)K(d[g])||e.push(x(g)+"="+x(d[g]));
U(a,"cust_params",e.join("&"));if(b._GA_googleCookieHelper){U(a,"cookie",b._GA_googleCookieHelper.v);b._GA_googleCookieHelper.T&&U(a,"cookie_enabled","1")}(b=kd(a,b,c))&&U(a,"cdm",b)},nd=function(a){ub();var b=window;T(a,"ga_vid",b.gaGlobal.vid);T(a,"ga_sid",b.gaGlobal.sid);T(a,"ga_hid",b.gaGlobal.hid);T(a,"ga_fc",b.gaGlobal.from_cookie);U(a,"ga_wpids",b.google_analytics_uacct)},od=function(a,b){for(var c in b){var d=b[c];K(d)||T(a,c,d)}},qd=function(a){var b=[];if(ca(window.GS_googleGetExpIdsForAdSense)==
"function"){var c=window.GS_googleGetExpIdsForAdSense();c&&b.push(c)}(c=pd(a.g.toString()))&&b.push(c);b.length>0&&U(a,"eid",b.join())};
S.prototype.i=function(a){this.n();qd(this);var b=new Date;gd(this,a);md(this,window,document);window.GA_googleEnv.getParameter("google_preview")!=h&&T(this,"gct",window.GA_googleEnv.getParameter("google_preview"));nd(this);ld(this,b,a,this.k);a={};Ma(a);od(this,a);T(this,"flash",Ka());this.b=this.b.substring(0,2E3);this.b=this.b.replace(/%\w?$/,"");if(this.fa){a=this.h=="iframe"?"html":"json_html";qb().registerAdBlockByType(a,this.b,f)}return this.b};
var ac=function(a){return a.u},V=function(a,b){var c=b.getAttribute("id");return c=c.substr(18,c.length-18)},rd=function(a,b,c,d){a='<ins style="position:relative;width:'+b+"px;height:"+c+'px;border:none;display:block;">'+d+"</ins>";return b='<ins style="position:relative;width:'+b+"px;height:"+c+'px;border:none;display:inline-table;">'+a+"</ins>"},sd=function(a,b,c,d,e,g){var i="google_ads_iframe_"+b,k=[];b="google_ads_div_"+b;var n="border:0px;left:0;position:absolute;top:0;";k.push("<iframe id=",
i," name=",i,' width="',e,'" height="',g,'" vspace="0" hspace="0" allowtransparency="true" ',"scrolling=",a.j?'"auto"':'"no"',' marginwidth="0" marginheight="0" frameborder="0" ','style="',n,'"',' src="',P(c),'"');d!=h&&k.push(' onload="',d,'"');k.push("></iframe>");c=[];k=k.join("");c.push("<div id=",b,">");c.push(rd(a,e,g,k));c.push("</div>");a=c.join("");document.write(a)},td=function(a,b,c){var d=O(a,c),e=d._width_,g=d._height_;d=d._html_;var i=document.createElement("iframe");i.id="google_ads_iframe_"+
c;i.name="google_ads_iframe_"+c;i.width=e;i.height=g;i.vspace=0;i.hspace=0;i.allowTransparency="true";i.scrolling="no";i.marginWidth=0;i.marginHeight=0;i.frameBorder=0;i.style.border=0;b=document.getElementById(b);i.style.position="absolute";i.style.top=0;i.style.left=0;var k=document.createElement("ins");k.style.width=e+"px";k.style.height=g+"px";k.style.border=0;k.style.display="block";k.style.position="relative";var n=document.createElement("ins");n.style.width=e+"px";n.style.height=g+"px";n.style.border=
0;n.style.display="inline-table";n.style.position="relative";k.appendChild(i);n.appendChild(k);b.appendChild(n);if(a.j){i.contentWindow.document.write(P(d));i.scrolling="auto"}else i.contentWindow.document.write(d);i.contentWindow.document.write("<script>document.close();<\/script>");Q(L(),c)};function ud(a,b){td(M(),a,b)}o("GA_googleCreateDomIframe",ud);
var vd=function(){var a=[],b=document.getElementsByTagName("base");if(b)for(var c=0,d=b.length;c<d;++c){var e=b[c],g=e.getAttribute("target");if(g){a.push({baseElement:e,originalTagValue:g});e.removeAttribute("target")}}return a},wd=function(a){if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b];d.baseElement.setAttribute("target",d.originalTagValue)}},xd=function(a){var b="http://"+fa()+"/pagead/inject_object_div.js";if(parseInt(ed(),10)>6)return j;if(a.indexOf(b)<0)return j;return f},yd=function(a,
b,c){if(a.j)c=P(c);a=vd();window.frames[b.name].contents=c;b.src=xd(c)?'javascript:document.write(window["contents"]);document.close();':'javascript:window["contents"]';wd(a)},zd=function(a,b,c){var d=V(a,b);try{var e=b.contentWindow?b.contentWindow.document:b.contentDocument;if(e==h)if(document.implementation&&document.implementation.createDocument)e=document.implementation.createDocument("",d,h);else if(typeof ActiveXObject!="undefined")e=new ActiveXObject("Msxml.DOMDocument");else return j;e.open("text/html",
"replace");a.j?e.write(P(c)):e.write(c);e.close()}catch(g){return j}return f},Ad=function(a,b){var c=V(a,b),d=Jc(L(),c);if(!d.$){d.$=f;d=O(a,c);var e=b.parentNode;if(d==h||d._html_==h)e.removeChild(b);else if(d._expandable_&&!(d._is_afc_&&d._is_3pas_))e.innerHTML=d._html_;else d._is_3pas_?yd(a,b,d._html_):zd(a,b,d._html_);Q(L(),c)}},Bd=function(a,b){var c="google_ads_div_"+b;c="<div id="+c+">";var d=O(a,b);if(d!=h){c+=d._html_;c+="\n</div>\n";document.write(c);Q(L(),b)}},Cd=function(a,b){var c="google_ads_div_"+
b,d="<div id="+c+">";d+="\n</div>\n";document.write(d);return c},Dd=function(a){if(!a.u)return f;if(Bc(L(),a.u)>0)return f;else if(Dc(L())==0)return j},Ed=function(a,b){Nb(J,"ga_srt",L().c.length,"_ga_start");if(a.f==h){a.f=b;for(var c in b)K(b[c])||Gc(L(),c)}else for(c in b)if(!K(b[c])){a.f[c]=b[c];Gc(L(),c)}var d=j;for(c in b)if(!K(b[c])){var e=b[c];if(d){e._cookies_=[Db(window._GA_googleCookieHelper)];d=j}e!=h&&e._cookies_!=h&&window._GA_googleCookieHelper.O(e)}};function Fd(a){Ed(M(),a)}
o("GA_googleSetAdContentsBySlot",Fd);function W(a){S.call(this,a);this.u=j;this.g=(new Date).getTime();this.h=a?"sync_sra":"sync"}q(W,S);W.prototype.n=function(){this.b=this.r;U(this,"correlator",this.g.toString());T(this,"output","json_html");T(this,"callback","GA_googleSetAdContentsBySlotForSync");this.k?T(this,"impl","ss"):T(this,"impl","s");Gd(this,L().c);if(!this.k){Hd(this,L().c,this.f);Id(this,L().c,this.f)}};
var Gd=function(a,b){for(var c=0,d=f,e=0;e<b.length;++e){var g=a.f&&a.f[b[e]];if(g)if(g._is_afc_==undefined){d=j;break}else c=2*c+(g._is_afc_?1:0)}d&&T(a,"prev_afc",c)},Id=function(a,b,c){if(b&&c)for(var d=b.length-2;d>=0;--d){var e=b[d];if((e=c[e])&&e._pstok_){U(a,"pstok",e._pstok_);break}}},Hd=function(a,b,c){if(b&&c){for(var d=[],e=[],g=b.length-1,i=0;i<g;i++){var k=b[i];if((k=c[k])&&k._cids_&&k._a2ids_){d.push(k._cids_[0]);e.push(k._a2ids_[0])}else{d.push("");e.push("")}}if(d.length>0){b=d.join(",");
e=e.join(",");U(a,"a2ids",e);U(a,"cids",b)}}},Jd=function(a,b){var c=L().a;c=c[b];if(c!=h)if(!a.z){a.i(c.t);Fc(L(),b);document.write("<script src = '"+a.b+"'><\/script>")}},Ld=function(a,b){Ed(a,b);if(a.k)if(L().c.length==1){var c=L().c[0];Kd(a,c);return}for(c in b)K(b[c])||Kd(a,c)};function Md(a){Ld(M(),a)}o("GA_googleSetAdContentsBySlotForSync",Md);W.prototype.m=function(){Dd(this)};var Nd=function(a){a.i(h);document.write("<script src = '"+a.b+"'><\/script>");Ec(L())};
W.prototype.p=function(a){L().c.push(a);Nb(J,"_ga_start",L().c.length);if(this.k)L().c.length==1?Nd(this):Kd(this,a);else Jd(this,a)};
var Od=function(a,b,c){if(b.google_js_backfill){a="script";c.write("<"+a+' src="'+Da+'"></'+a+">")}},Kd=function(a,b){Pd(a,window,document,b)},Pd=function(a,b,c,d){var e=Jc(L(),d);if(e!=h){e=O(a,d);Hc(L(),d);if(e==h||e._empty_){Od(a,b,c,d);Q(L(),d)}else if(a.J&&!a.j)Q(L(),d);else if(e._snippet_&&!e._is_afc_&&!a.j)Bd(a,d);else if(b.navigator.userAgent.indexOf("MSIE ")>0){c="GA_googleSyncAdSlotLoaded(this);";var g="about:blank";if(b=b.GA_googleEnv.getParameter("google_domain_reset_url")){var i=Kb(b.match(Jb)[3]||
h);if(i===h||i.indexOf(document.domain)>=0)g=b}sd(a,d,g,c,e._width_,e._height_)}else{a=Cd(a,d);c.write("<script>GA_googleCreateDomIframe('"+a+"' ,'"+d+"');<\/script>")}}},Qd=function(a,b){V(a,b);L();Ad(a,b)};function Rd(a){Qd(M(),a)}o("GA_googleSyncAdSlotLoaded",Rd);function X(a){S.call(this,a);this.g=(new Date).getTime();this.h="async"}q(X,S);
X.prototype.n=function(){this.b=this.r;Sd(this);U(this,"correlator",this.g.toString());T(this,"output","json_html");T(this,"callback","GA_googleSetAdContentsBySlot");T(this,"impl","a")};var Sd=function(a){a.delay=500;var b=window.GA_googleEnv.getParameter("google_async_delay");if(b!=h)a.delay=1E3*b};X.prototype.m=function(){if(Dd(this))this.z||window.setTimeout("GA_googleReallyFetchAds();",20)};
var Td=function(a){if(Bc(L(),a.u)!=0){var b=document.getElementsByTagName("head")[0];if(a.k){var c=document.createElement("script");c.src=a.i(h);b.appendChild(c);Ec(L())}else{var d=L().a;for(var e in d)if(!K(d[e])){c=document.createElement("script");c.src=a.i(e);b.appendChild(c);Fc(L(),e)}}}};function Ud(){Td(M())}o("GA_googleReallyFetchAds",Ud);
X.prototype.p=function(a){var b=Jc(L(),a);if(b!=h){L().c.push(a);b="GA_googleAsyncAdSlotLoaded(this);";var c=N(L(),a);sd(this,a,"about:blank",b,c._width_,c._height_)}};var Wd=function(a,b){V(a,b);L();!a.z&&!a.J&&Vd(a,b)};function Xd(a){Wd(M(),a)}o("GA_googleAsyncAdSlotLoaded",Xd);var Vd=function(a,b){var c=V(a,b),d=Jc(L(),c);if(a.f==h||a.f[c]==h){if(!(d.ca>30)){window.setTimeout(function(){Vd(M(),b)},a.delay);d.ca++}}else Ad(a,b)};X.prototype.G=function(){};
function Y(a){S.call(this,a);this.g=(new Date).getTime();this.P=f;this.h="iframe"}q(Y,S);Y.prototype.n=function(){this.b=this.r;U(this,"correlator",this.g.toString());T(this,"output","html");T(this,"impl","ifr")};Y.prototype.m=function(){Dd(this)};var Yd=function(a,b){var c;if(a.k){a.i(h);c=a.b+"&currentslot="+x(b)}else c=a.i(b);return c};Y.prototype.p=function(a){var b=N(L(),a);if(b!=h){L().c.push(a);if(!this.z){var c=Yd(this,a);sd(this,a,c,h,b._width_,b._height_)}}};
var Zd=function(){if(Ia("msie")&&!window.opera){var a=ed();return a>5}else if(Ia("firefox")){a=navigator.userAgent.indexOf("Firefox")+8;var b=parseInt(navigator.userAgent.charAt(a),10);navigator.userAgent.slice(a);return b>1}return j},$d=function(){if(window.google_delayFetch&&Zd())return"async";return"sync"},Sb=function(a){var b=h;if(typeof a!="undefined"&&a!=h)b=a;else{b=window.GA_googleEnv.getParameter("google_ad_impl");if(b==h)b=$d()}switch(b){case "async":return new X(j);case "sync":return new W(j);
case "sync_sra":return new W(f);case "iframe":return new Y(j);default:return new W(j)}},Z;function L(){Z||(Z=new gc(rb));return Z}function fc(a){delete Z;Z=a}var $;function M(){$||($=h);return $}function Rb(a){delete $;$=a}if(typeof window.GA_googleEnv=="undefined")window.GA_googleEnv=new lc;if(typeof window.GA_googleAdCapture=="undefined")window.GA_googleAdCapture=new nc;if(window._GA_googleCookieHelper==h)window._GA_googleCookieHelper=new I(h);
function pd(a){var b=qb(),c=b.getEid();if(c==""){if(c=ae(window)){var d=b.getOsdMode();if(c=="36815006"||c=="36813008"){b.setValidOutputTypes(["html","json_html"]);d=c=="36815006"?1:0}b.setupOsd(d,c,a);(a=M())&&ad(a)}}else if(c!="36815006"&&c!="36815005"&&c!="36813008"&&c!="36813007")c="";return c}function ae(a){if((a.google_unique_id||0)!=0)return"";a=La(["36815005","36815006"],Va);if(a=="")a=La(["36813007","36813008"],Wa);return a}J.tick("js_parse","js_load");J.tick("jl");})()
