d = new dTree("d");
<!--
d.add("0","-1","Groovy指南","");
d.add("1","0","实战 Groovy: 美妙的操作符","my_data/实战_Groovy__美妙的操作符.htm");
d.add("2","0","groovy风格的动态面向对象","my_data/groovy风格的动态面向对象.md.html");
d.add("3","0","注意CodeCache的设置","my_data/注意CodeCache的设置.htm");
d.add("4","0","使用Groovy需要注意的几个点","my_data/使用Groovy需要注意的几个点.htm");
d.add("5","0","嵌入Groovy大全(java中调用groovy)","my_data/嵌入Groovy.htm");
d.add("6","0","Java中使用Groovy实现自定义表达式解析","my_data/Java中使用Groovy实现自定义表达式解析.htm");
d.add("7","0","获取Spring的WebApplicationContext","my_data/获取Spring的WebApplicationContext.htm");
d.add("8","0","Groovy操纵集合秘籍","my_data/Groovy操纵集合秘籍.html");
d.add("9","0","便捷，轻巧的Groovy数据库操作","my_data/便捷，轻巧的Groovy数据库操作.htm");
d.add("10","0","Groovy在Spring中的简单使用","my_data/Groovy在Spring中的简单使用.htm");
d.add("11","0","Gradle 打包 Groovy 脚本成 jar与上传到maven repository","my_data/Gradle打包Groovy脚本成 jar与上传到maven repository.htm");
d.add("12","0","The MarkupTemplateEngine","my_data/markup-template-engine.html");
d.add("13","0","官方例子","");
d.add("14","13","Groovy - Calculating a SHA1 hash for large files","my_data/官方例子/Groovy - Calculating a SHA1 hash for large files.htm");
d.add("15","13","Groovy - ConfigSlurper","my_data/官方例子/Groovy - ConfigSlurper.htm");
d.add("16","13","Groovy - Convert SQL Result To XML","my_data/官方例子/Groovy - Convert SQL Result To XML.htm");
d.add("17","13","Groovy - Creating Larger XML using StreamingMarkupBuilder","my_data/官方例子/Groovy - Creating Larger XML using StreamingMarkupBuilder.htm");
d.add("18","13","Groovy - Creating XML using Groovy's MarkupBuilder","my_data/官方例子/Groovy - Creating XML using Groovy's MarkupBuilder.htm");
d.add("19","13","Groovy - GPath","my_data/官方例子/Groovy - GPath.htm");
d.add("20","13","Groovy - Groovy Templates","my_data/官方例子/Groovy - Groovy Templates.htm");
d.add("21","13","Groovy - Reading XML using Groovy's XmlSlurper","my_data/官方例子/Groovy - Reading XML using Groovy's XmlSlurper.htm");
d.add("22","13","Groovy - Updating XML with XmlSlurper","my_data/官方例子/Groovy - Updating XML with XmlSlurper.htm");
d.add("23","13","Groovy - Validating XML with a W3C XML Schema","my_data/官方例子/Groovy - Validating XML with a W3C XML Schema.htm");
d.add("24","13","Working with JMX","my_data/官方例子/The Groovy programming language - Working with JMX.htm");
d.add("25","0","秘诀","");
d.add("26","25","Map Shortcuts","my_data/秘诀/Map_Shortcuts.htm");
d.add("27","25","Optional Parameters/Default Values","my_data/秘诀/Optional_Parameters_Default_Values.htm");
d.add("28","25","Using Shell Wildcards in Groovy Scripts","my_data/秘诀/Using_Shell_Wildcards_in_Groovy_Scripts.htm");
d.add("29","25","Waiting for a Shell Command to Finish Before Continuing","my_data/秘诀/Waiting_for_a_Shell_Command_to_Finish_Before_Continuing.htm");
d.add("30","25","Calling Another Groovy Script","my_data/秘诀/Calling_Another_Groovy_Script.htm");
d.add("31","25","Listing All Files in a Directory","my_data/秘诀/Listing_All_Files_in_a_Directory.htm");
d.add("32","25","Copying Files","my_data/秘诀/Copying_Files.htm");
d.add("33","25","Using AntBuilder to Copy a File","my_data/秘诀/Using_AntBuilder_to_Copy_a_File.htm");
d.add("34","25","Creating a ZIP File/Tarball","my_data/秘诀/Creating_a_ZIP_File_Tarball.htm");
d.add("35","25","Unzipping/Untarring Files","my_data/秘诀/Unzipping_Untarring_Files.htm");
d.add("36","25","Dealing with XML Attributes","my_data/秘诀/Dealing_with_XML_Attributes.htm");
d.add("37","25","Navigating Deeply Nested XML","my_data/秘诀/Navigating_Deeply_Nested_XML.htm");
d.add("38","25","Parsing an XML Document with Namespaces","my_data/秘诀/Parsing_an_XML_Document_with_Namespaces.htm");
d.add("39","25","Creating Namespaced XML Using MarkupBuilder","my_data/秘诀/Creating_Namespaced_XML_Using_MarkupBuilder.htm");
d.add("40","25","Understanding the Difference Between MarkupBuilder and StreamingMarkupBuilder","my_data/秘诀/Understanding_the_Difference_Between_MarkupBuilder_and_StreamingMarkupBuilder.htm");
d.add("41","25","Creating Parts of the XML Document Separately","my_data/秘诀/Creating_Parts_of_the_XML_Document_Separately.htm");
d.add("42","25","Creating HTML on the Fly","my_data/秘诀/Creating_HTML_on_the_Fly.htm");
d.add("43","25","Making an HTTP GET Request","my_data/秘诀/Making_an_HTTP_GET_Request.htm");
d.add("44","25","Making an HTTP POST Request","my_data/秘诀/Making_an_HTTP_POST_Request.htm");
d.add("45","25","Discovering the Class","my_data/秘诀/Discovering_the_Class.htm");
d.add("46","25","Discovering the Fields of a Class","my_data/秘诀/Discovering_the_Fields_of_a_Class.htm");
d.add("47","25","Checking for the Existence of a Field","my_data/秘诀/Checking_for_the_Existence_of_a_Field.htm");
d.add("48","25","Discovering the Methods of a Class","my_data/秘诀/Discovering_the_Methods_of_a_Class.htm");
d.add("49","25","Checking for the Existence of a Method","my_data/秘诀/Checking_for_the_Existence_of_a_Method.htm");
d.add("50","25","Calling Methods That Don't Exist (invokeMethod)","my_data/秘诀/Calling_Methods_That_Don't_Exist_(invokeMethod).htm");
d.add("51","25","Adding Methods to a Class Dynamically (Categories)","my_data/秘诀/Adding_Methods_to_a_Class_Dynamically_(Categories).htm");
d.add("52","25","Adding Methods to a Class Dynamically (ExpandoMetaClass)","my_data/秘诀/Adding_Methods_to_a_Class_Dynamically_(ExpandoMetaClass).htm");
d.add("53","0","Json","");
d.add("54","53","Groovy 1.8 新特性: 原生 JSON 支持","my_data/Json/Groovy_1.8_新特性__原生_JSON_支持.htm");
d.add("55","53","groovy 操作json实例","my_data/Json/groovy 操作json实例.htm");
d.add("56","53","groovy JsonBuilder将对象转向json","my_data/Json/groovy_JsonBuilder将对象转向json.htm");
d.add("57","53","Groovy Simple JSON array builder","my_data/Json/Groovy_Simple_JSON_array_builder.htm");
d.add("58","53","Writing json output from a groovlet | Stuff I've learned recently...","my_data/Json/Writing json output from a groovlet.htm");
d.add("59","0","Servlet","");
d.add("60","59","获取Spring的WebApplicationContext","my_data/获取Spring的WebApplicationContext.htm");
d.add("61","59","groovy:groovyservlet 乱码问题,解决","my_data/groovy-groovyservlet 乱码问题,解决.htm");
d.add("62","59","Groovy笔记(12)_Groovlet","my_data/Groovy笔记(12)_Groovlet.htm");
d.add("63","59","用groovyServlet和TemplateServlet快速开发网页","my_data/用GroovyServlet和TemplateServlet快速开发网页.htm");
d.add("64","59","用 Groovlet 和 GSP 进行动态服务器端编程","my_data/用_Groovy_打造服务器端.htm");
d.add("65","59","groovy及其TemplateServlet的编码问题","my_data/Groovy及其TemplateServlet的编码问题.htm");
d.add("66","0","Sql","");
d.add("67","66","Groovy Sql 知识点整理","my_data/Sql/Groovy_Sql_知识点整理.md.html");
d.add("68","66","Notes about Groovy's DataSet","my_data/Sql/Notes_about_Groovy's_DataSet.htm");
d.add("69","66","Use Sql under transaction","my_data/Sql/Use Sql under transaction.htm");
d.add("70","66","Batch Sql","my_data/Sql/Batch_Sql.htm");
d.add("71","0","Java8","");
d.add("72","71","Groovy compiler does not accept java 8 Lambdas","my_data/Java8/Groovy_compiler_does_not_accept_java_8_Lambdas.htm");
d.add("73","71","Java 8 lambdas vs. Groovy closures (part 1 of 2)","my_data/Java8/Java_8_lambdas_vs._Groovy_closures_(part_1_of_2).htm");
d.add("74","71","Java 8 lambdas vs. Groovy closures (part 2 of 2)","my_data/Java8/Java_8_lambdas_vs._Groovy_closures_(part_2_of_2).htm");
d.add("75","71","Java 8 Lambdas vs Groovy Closures Compactness: Grouping And Summing","my_data/Java8/Java_8_Lambdas_vs_Groovy_Closures_Compactness__Grouping_And_Summing.htm");
d.add("76","0","Goodness(精华)","");
d.add("77","76","Add Methods Dynamically to Classes with ExpandoMetaClass","my_data/Goodness/Add Methods Dynamically to Classes with ExpandoMetaClass.htm");
d.add("78","76","Annotion-Builder详细解释","my_data/Goodness/Annotion-Builder详细解释.htm");
d.add("79","76","Annotion-Create a Singleton Class","my_data/Goodness/Annotion-Create a Singleton Class.htm");
d.add("80","76","Annotion-Easy toString Creation for Our Classes","my_data/Goodness/Annotion-Easy toString Creation for Our Classes.htm");
d.add("81","76","Annotion-Generate equals and hashcode Methods with EqualsAndHashCode Annotation","my_data/Goodness/Annotion-Generate equals and hashcode Methods with EqualsAndHashCode Annotation.htm");
d.add("82","76","Annotion-Making a Class Immutable","my_data/Goodness/Annotion-Making a Class Immutable.htm");
d.add("83","76","Annotion-Tuple Constructor Creation","my_data/Goodness/Annotion-Tuple Constructor Creation.htm");
d.add("84","76","Annotion-Use Builder AST Transformation for Fluent API","my_data/Goodness/Annotion-Use Builder AST Transformation for Fluent API.htm");
d.add("85","76","Base-Create Indexed Property Getter and Setter Methods","my_data/Goodness/Base-Create Indexed Property Getter and Setter Methods.htm");
d.add("86","76","Base-Formatted Strings with sprintf","my_data/Goodness/Base-Formatted Strings with sprintf.htm");
d.add("87","76","Base-Padding Strings","my_data/Goodness/Base-Padding Strings.htm");
d.add("88","76","Base-the Switch Statement","my_data/Goodness/Base-the Switch Statement.htm");
d.add("89","76","Base-the With Method","my_data/Goodness/Base-the With Method.htm");
d.add("90","76","Base-Transform String into Enum","my_data/Goodness/Base-Transform String into Enum.htm");
d.add("91","76","Base-Working with Arrays","my_data/Goodness/Base-Working with Arrays.htm");
d.add("92","76","Builder-Create Simple Builders with Closures","my_data/Goodness/Builder-Create Simple Builders with Closures.htm");
d.add("93","76","Builder-Solve Naming Conflicts with Builders","my_data/Goodness/Builder-Solve Naming Conflicts with Builders.htm");
d.add("94","76","Closure as a Class","my_data/Goodness/Closure as a Class.htm");
d.add("95","76","Collection-Determine Min and Max Entries in a Map","my_data/Goodness/Collection-Determine Min and Max Entries in a Map.htm");
d.add("96","76","Collection-Drop or Take Elements with Condition","my_data/Goodness/Collection-Drop or Take Elements with Condition.htm");
d.add("97","76","Collection-Finding Data in Collections","my_data/Goodness/Collection-Finding Data in Collections.htm");
d.add("98","76","Collection-Getting the Indices of a Collection","my_data/Goodness/Collection-Getting the Indices of a Collection.htm");
d.add("99","76","Collection-GroupBy with Multiple Closures","my_data/Goodness/Collection-GroupBy with Multiple Closures.htm");
d.add("100","76","Collection-New Methods to Sort and Remove Duplicates From Collection","my_data/Goodness/Collection-New Methods to Sort and Remove Duplicates From Collection.htm");
d.add("101","76","Collection-Observable Map and List","my_data/Goodness/Collection-Observable Map and List.htm");
d.add("102","76","Collection-Pop And Push Items In a List","my_data/Goodness/Collection-Pop And Push Items In a List.htm");
d.add("103","76","Collection-Revisited Getting the Sum of Items in a Collection","my_data/Goodness/Collection-Revisited Getting the Sum of Items in a Collection.htm");
d.add("104","76","Collection-Take and Drop Items from a List","my_data/Goodness/Collection-Take and Drop Items from a List.htm");
d.add("105","76","Collection-Using Lists and Maps As Constructors","my_data/Goodness/Collection-Using Lists and Maps As Constructors.htm");
d.add("106","76","conf-Check Configuration Property Is Set In ConfigObject","my_data/Goodness/conf-Check Configuration Property Is Set In ConfigObject.htm");
d.add("107","76","conf-Using ConfigSlurper with Configuration Scripts","my_data/Goodness/conf-Using ConfigSlurper with Configuration Scripts.htm");
d.add("108","76","Date-Convert Date to java.sql.Timestamp","my_data/Goodness/Date-Convert Date to java.sql.Timestamp.htm");
d.add("109","76","Date-Create New Date or Calendar from Existing and Set Property Value","my_data/Goodness/Date-Create New Date or Calendar from Existing and Set Property Value.htm");
d.add("110","76","IO-Transforming Reader Input to Writer Output","my_data/Goodness/IO-Transforming Reader Input to Writer Output.htm");
d.add("111","76","IO-Use Connection Parameters to Get Text From URL","my_data/Goodness/IO-Use Connection Parameters to Get Text From URL.htm");
d.add("112","76","JSON-Build JSON with JsonBuilder and Pretty Print JSON Text","my_data/Goodness/JSON-Build JSON with JsonBuilder and Pretty Print JSON Text.htm");
d.add("113","76","JSON-Parse JSON with JsonSlurper","my_data/Goodness/JSON-Parse JSON with JsonSlurper.htm");
d.add("114","76","JSON-Streaming JSON with StreamingJsonBuilder","my_data/Goodness/JSON-Streaming JSON with StreamingJsonBuilder.htm");
d.add("115","76","Parsing Commandline Arguments with CliBuilder","my_data/Goodness/Parsing Commandline Arguments with CliBuilder.htm");
d.add("116","76","Regular-Matchers for Regular Expressions","my_data/Goodness/Regular-Matchers for Regular Expressions.htm");
d.add("117","76","Regular-Using Regular Expression Pattern Class","my_data/Goodness/Regular-Using Regular Expression Pattern Class.htm");
d.add("118","76","Using Groovy for Git Hooks","my_data/Goodness/Using Groovy for Git Hooks.htm");
d.add("119","76","XML-Change XML Structure","my_data/Goodness/XML-Change XML Structure.htm");
d.add("120","76","XML-Pretty Print XML","my_data/Goodness/XML-Pretty Print XML.htm");
d.add("121","76","File-Traversing a Directory","my_data/Goodness/File-Traversing a Directory.html");
d.add("122","76","File-Working on Files or Directories (or Both) with FileType","my_data/Goodness/File-Working on Files or Directories (or Both) with FileType.html");
d.add("123","76","Use Expanded Variables in SQL GString Query","my_data/Goodness/Use_Expanded_Variables_in_SQL_GString_Query.htm");
d.add("124","0","性能","");
d.add("125","124","Groovy与Java集成的方式","my_data/性能/Groovy与Java集成的方式.html");
d.add("126","124","Groovy引发的PermGen区爆满问题定位与解决","my_data/性能/Groovy引发的PermGen区爆满问题定位与解决.html");
d.add("127","124","Groovy PermGen Full GC 问题解析以及解决","my_data/性能/Groovy PermGen Full GC 问题解析以及解决.html");
d.add("128","124","在Java里整合Groovy脚本的一个陷阱","my_data/性能/在Java里整合Groovy脚本的一个陷阱.html");
d.add("129","0","Groovy 2.0新特性","my_data/Groovy 2.0新特性.htm");
d.add("130","0","Groovy的脚本引擎-GroovyScriptEngine","my_data/Groovy的脚本引擎-GroovyScriptEngine_.htm");
d.add("131","0","JAVA嵌入运行Groovy脚本","my_data/JAVA嵌入运行Groovy脚本.htm");
d.add("132","0","java 中调用 groovy","my_data/java中调用groovy.htm");
d.add("133","0","Groovy Goodness: New Dollar Slashy Strings - Messages from mrhaki","my_data/(新的字符串定义符)New Dollar Slashy Strings.htm");
d.add("134","0","Groovy 与 DSL","my_data/Groovy与DSL.htm");
d.add("135","0","groovy的DSL(2)","my_data/Groovy的DSL(2).htm");
d.add("136","0","Groovy解惑-Closure中的delegate","my_data/Groovy解惑-Closure中的delegate.htm");
d.add("137","0","Groovy解惑-Closure中的owner,this,delegate","my_data/Groovy解惑-Closure中的owner,this,delegate.htm");
d.add("138","0","java程序员为什么使用Groovy","my_data/java程序员为什么使用Groovy.htm");
d.add("139","0","打动你朋友的11条Groovy超炫代码","my_data/打动你朋友的11条Groovy超炫代码.htm");
d.add("140","0","即时编译和打包您的 Groovy 脚本","my_data/即时编译和打包您的 Groovy 脚本/index.html");
d.add("141","0","嵌入Groovy脚本时添加一些默认import","my_data/嵌入Groovy脚本时添加一些默认import.htm");
d.add("142","0","如何判断文件是文本还是二进制","my_data/如何判断文件是文本还是二进制.htm");
d.add("143","0","Groovy 1.8 新特性: 增强的 AST","my_data/Groovy_1.8_新特性__增强的_AST.htm");
d.add("144","0","闭包作为注释的参数","my_data/闭包作为注释的参数.htm");
d.add("145","0","使用 Groovy 获取classpath中的资源","my_data/使用_Groovy_获取代码树中的资源.htm");
d.add("146","0","在 Gradle 脚本中处理Manifest: ClassPath","my_data/Gradle_脚本中处理Manifest__ClassPath.htm");
d.add("147","0","Customizing Groovy compilation process(阻止System.exit())","my_data/Customizing Groovy compilation process(阻止System.exit()).htm");
d.add("148","0","Groovy: 比JavaBean好用的GroovyBean - zjumty - ITeye技术网站","my_data/Groovy- 比JavaBean好用的GroovyBean.htm");
d.add("149","0","实战 Groovy: 构建和解析 XML","my_data/实战_Groovy__构建和解析_XML.htm");
d.add("150","0","Groovy中XmlParser和XmlSlurper异同","my_data/Groovy中XmlParser和XmlSlurper异同.html");
d.add("151","0","Robust HTML parsing the Groovy way","my_data/Robust_HTML_parsing_the_Groovy_way.htm");
d.add("152","0","Groovy用inject方法构造Map","my_data/Groovy用inject方法构造Map.htm");
d.add("153","0","List对象的transpose和inject方法的使用","my_data/List对象的transpose和inject方法的使用.htm");
d.add("154","0","Groovy闭包详解","my_data/Groovy闭包详解.htm");
d.add("155","0","实战 Groovy: for each 剖析","my_data/实战_Groovy__for_each_剖析.htm");
d.add("156","0","用Groovy模板写MyBatis动态SQL","my_data/用Groovy模板写MyBatis动态SQL.htm");
document.write(d);
//-->
